### ISSUE TITLE
Metacharecters in time

### ISSUE THREAD

**Issue by perfidia** [perfidia/regexpgen#15]
``` python
>>> print regexpgen.time("%H:%M", "12:24", "17:59")
^(12\:(2[4-9]|[3-4][0-9]|5[0-9])|(1[3-5]|16)\:[0-5][0-9]|17\:[0-5][0-9])$
```

AFAIR colon is not a metacharacter, so there is no need to escape it.

**Comment by Venomo** [comment]
It's because we use re.escape internally and it escapes colon. 

print re.escape(":")
\:
