### ISSUE TITLE
Inconsistence in API

### ISSUE THREAD

**Issue by perfidia** [perfidia/regexpgen#18]
``` python
regexpgen.__init__:
def integer(frmt, minV = None, maxV = None): # here we have V
def nnint(frmt, minV = None, maxV = None):
def real(format, min = None, max = None): # but no V here, format instead of frmt
def time(format, min = None, max = None): # the same issue with format

regexpgen.builder.RegexBuilder # where is p in RegexBuilder?
def createIntegerRegex(self, frmt, minV, maxV):
def createRealRegex(self, frmt, minV, maxV):
def createNNIntegerRegex(self, frmt, minV, maxV):
def createTimeRegex(self, frmt, minT, maxT): # not V but T
```

Please make it consistent.

**Comment by Venomo** [comment]
Inconsistencies fixed, but I don't understand  "# where is p in RegexBuilder?". Could you elaborate?

**Comment by perfidia** [comment]
IMO these are the most common used shortcuts for regular expressions: re, regex, regexp. The last one was used in our project. 
That is why the project's name is regexPgen, the package is called regexPgen. However the class to generate regular expressions has name without letter p :)

**Comment by Venomo** [comment]
Oh, now we get it, fixed.
