### ISSUE TITLE
nnint function accepts None as a first parameter (expected ValueError)

### ISSUE THREAD

**Issue by perfidia** [perfidia/regexpgen#5]
print regexpgen.integer(None)

Traceback (most recent call last):
  File "/git/regexpgen/src/main.py", line 11, in <module>
    print regexpgen.integer(None)
  File "/git/regexpgen/src/regexpgen/**init**.py", line 85, in integer
    if (format not in ["%d", "%0d"]) and not re.match("^%0[0-9]+d$", format):
  File "/usr/lib/python2.7/re.py", line 137, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or buffer

**Comment by perfidia** [comment]
The same with other functions.

**Comment by Venomo** [comment]
Fixed.

**Comment by perfidia** [comment]
The following combinations are also problematic:

regexpgen.integer("%d", None)
regexpgen.integer("%d", None, 13)
regexpgen.integer("%d", 12, None)
regexpgen.integer("%d", None, None)

**Comment by Venomo** [comment]
Problematic in what sense? It seems to me that the results are valid:

^(0_(-?([0-9]+)))$
^(-?(0_([0-9]|1[0-3]))|-(0_(1[4-9]|[2-9][0-9]|[1-9][0-9]{2}[0-9]_)))$
^(0_(1[2-9]|[2-9][0-9]|[1-9][0-9]{2}[0-9]_))$
^(0*(-?([0-9]+)))$

**Comment by perfidia** [comment]
I forgot to add print function. It works OK.
