### ISSUE TITLE
re.match(regexpgen.real("%lf", -0.01, 1.5), "1.5") returns None

### ISSUE THREAD

**Issue by perfidia** [perfidia/regexpgen#6]
print regexpgen.real("%lf", -0.01, 1.5)
print re.match(regexpgen.real("%lf", -0.01, 1.5), "1.5")

^(-?(0_(0.((00)[0-9]_|010_)))|0_(0(.(0[1-9]|1|[2-9])[0-9]_)|1(.(0|1|[2-3]|4)[0-9]_)|1.500*))$
None

IMO problem is here: 1.500*

**Comment by joannabinczewska** [comment]
Done.
