### ISSUE TITLE
re.match(r.real("%lf", -10.0, 10.00000000001), "10.000000000001") returns None

### ISSUE THREAD

**Issue by mkurek** [perfidia/regexpgen#7]
re.match(r.real("%lf", -10.0, 10.00000000001), "10.000000000001") returns None but re.match(r.real("%lf", -10.0, 10.00001), "10.000000000001") works fine

**Comment by Venomo** [comment]
print re.match(regexpgen.real("%lf", -10.0, 10.00000000001), "10.000000000001"), float(10.00000000001)
print re.match(regexpgen.real("%lf", -10.0, 10.0000000001),  "10.000000000001"), float(10.0000000001)
print re.match(regexpgen.real("%lf", -10.0, 10.000000001),   "10.000000000001"), float(10.000000001)
print re.match(regexpgen.real("%lf", -10.0, 10.00000001),    "10.000000000001"), float(10.00000001)
print re.match(regexpgen.real("%lf", -10.0, 10.0000001),     "10.000000000001"), float(10.0000001)
print re.match(regexpgen.real("%lf", -10.0, 10.000001),      "10.000000000001"), float(10.000001)
print re.match(regexpgen.real("%lf", -10.0, 10.00001),       "10.000000000001"), float(10.00001)

None 10.0
<_sre.SRE_Match object at 0x0000000001E76AA0> 10.0000000001
<_sre.SRE_Match object at 0x0000000001E76AA0> 10.000000001
<_sre.SRE_Match object at 0x0000000001E76AA0> 10.00000001
<_sre.SRE_Match object at 0x0000000001E76AA0> 10.0000001
<_sre.SRE_Match object at 0x0000000001E76AA0> 10.000001
<_sre.SRE_Match object at 0x0000000001E76AA0> 10.00001

If float() doesn't know about the .00..01 neither we do. It would be possible (although complicated) to detect, but I think we can assume that regexpgen user knows about precision characteristics of float.

**Comment by perfidia** [comment]
Please add info about it in documentation.

**Comment by Venomo** [comment]
Done.
