### ISSUE TITLE
String concatenations (optimization)

### ISSUE THREAD

**Issue by mkurek** [perfidia/regexpgen#8]
You should use ''.join([...]) instead of concatenation by += (**init**.py, concatenate method)

I suggest storing all generated string in a list and at the end join strings in the list into one string. So instead of:
r = ""
for i in ...:
    r += i
return r

do sth like this:

r = []
for i in ...:
   r.append(i)
return ''.join(r)

**Comment by Venomo** [comment]
Done, thanks.

**Comment by perfidia** [comment]
I don't see any changes in repo.

**Comment by Venomo** [comment]
It's at builder.py: 48, 628, 669, 824.

**Comment by perfidia** [comment]
Please change the following code:

``` python
# line 628 in builder.py
result = []
result.append("(")
```

to

``` python
result = ["(", ]
```

The latter is faster.

**Comment by Venomo** [comment]
Done.
